/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tapink.doctornfc.patients;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Prescription implements org.apache.thrift.TBase<Prescription, Prescription._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Prescription");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PATIENT_FIELD_DESC = new org.apache.thrift.protocol.TField("patient", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField MEDICATION_FIELD_DESC = new org.apache.thrift.protocol.TField("medication", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField TABLETS_FIELD_DESC = new org.apache.thrift.protocol.TField("tablets", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField TABLET_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("tablet_size", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField HOURS_BETWEEN_DOSES_FIELD_DESC = new org.apache.thrift.protocol.TField("hours_between_doses", org.apache.thrift.protocol.TType.I32, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PrescriptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PrescriptionTupleSchemeFactory());
  }

  public String id; // required
  public Patient patient; // required
  public Medication medication; // required
  public int tablets; // required
  public int tablet_size; // required
  public int hours_between_doses; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    PATIENT((short)2, "patient"),
    MEDICATION((short)3, "medication"),
    TABLETS((short)4, "tablets"),
    TABLET_SIZE((short)5, "tablet_size"),
    HOURS_BETWEEN_DOSES((short)6, "hours_between_doses");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // PATIENT
          return PATIENT;
        case 3: // MEDICATION
          return MEDICATION;
        case 4: // TABLETS
          return TABLETS;
        case 5: // TABLET_SIZE
          return TABLET_SIZE;
        case 6: // HOURS_BETWEEN_DOSES
          return HOURS_BETWEEN_DOSES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TABLETS_ISSET_ID = 0;
  private static final int __TABLET_SIZE_ISSET_ID = 1;
  private static final int __HOURS_BETWEEN_DOSES_ISSET_ID = 2;
  private BitSet __isset_bit_vector = new BitSet(3);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PATIENT, new org.apache.thrift.meta_data.FieldMetaData("patient", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Patient.class)));
    tmpMap.put(_Fields.MEDICATION, new org.apache.thrift.meta_data.FieldMetaData("medication", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Medication.class)));
    tmpMap.put(_Fields.TABLETS, new org.apache.thrift.meta_data.FieldMetaData("tablets", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TABLET_SIZE, new org.apache.thrift.meta_data.FieldMetaData("tablet_size", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.HOURS_BETWEEN_DOSES, new org.apache.thrift.meta_data.FieldMetaData("hours_between_doses", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Prescription.class, metaDataMap);
  }

  public Prescription() {
  }

  public Prescription(
    String id,
    Patient patient,
    Medication medication,
    int tablets,
    int tablet_size,
    int hours_between_doses)
  {
    this();
    this.id = id;
    this.patient = patient;
    this.medication = medication;
    this.tablets = tablets;
    setTabletsIsSet(true);
    this.tablet_size = tablet_size;
    setTablet_sizeIsSet(true);
    this.hours_between_doses = hours_between_doses;
    setHours_between_dosesIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Prescription(Prescription other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetPatient()) {
      this.patient = new Patient(other.patient);
    }
    if (other.isSetMedication()) {
      this.medication = new Medication(other.medication);
    }
    this.tablets = other.tablets;
    this.tablet_size = other.tablet_size;
    this.hours_between_doses = other.hours_between_doses;
  }

  public Prescription deepCopy() {
    return new Prescription(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.patient = null;
    this.medication = null;
    setTabletsIsSet(false);
    this.tablets = 0;
    setTablet_sizeIsSet(false);
    this.tablet_size = 0;
    setHours_between_dosesIsSet(false);
    this.hours_between_doses = 0;
  }

  public String getId() {
    return this.id;
  }

  public Prescription setId(String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public Patient getPatient() {
    return this.patient;
  }

  public Prescription setPatient(Patient patient) {
    this.patient = patient;
    return this;
  }

  public void unsetPatient() {
    this.patient = null;
  }

  /** Returns true if field patient is set (has been assigned a value) and false otherwise */
  public boolean isSetPatient() {
    return this.patient != null;
  }

  public void setPatientIsSet(boolean value) {
    if (!value) {
      this.patient = null;
    }
  }

  public Medication getMedication() {
    return this.medication;
  }

  public Prescription setMedication(Medication medication) {
    this.medication = medication;
    return this;
  }

  public void unsetMedication() {
    this.medication = null;
  }

  /** Returns true if field medication is set (has been assigned a value) and false otherwise */
  public boolean isSetMedication() {
    return this.medication != null;
  }

  public void setMedicationIsSet(boolean value) {
    if (!value) {
      this.medication = null;
    }
  }

  public int getTablets() {
    return this.tablets;
  }

  public Prescription setTablets(int tablets) {
    this.tablets = tablets;
    setTabletsIsSet(true);
    return this;
  }

  public void unsetTablets() {
    __isset_bit_vector.clear(__TABLETS_ISSET_ID);
  }

  /** Returns true if field tablets is set (has been assigned a value) and false otherwise */
  public boolean isSetTablets() {
    return __isset_bit_vector.get(__TABLETS_ISSET_ID);
  }

  public void setTabletsIsSet(boolean value) {
    __isset_bit_vector.set(__TABLETS_ISSET_ID, value);
  }

  public int getTablet_size() {
    return this.tablet_size;
  }

  public Prescription setTablet_size(int tablet_size) {
    this.tablet_size = tablet_size;
    setTablet_sizeIsSet(true);
    return this;
  }

  public void unsetTablet_size() {
    __isset_bit_vector.clear(__TABLET_SIZE_ISSET_ID);
  }

  /** Returns true if field tablet_size is set (has been assigned a value) and false otherwise */
  public boolean isSetTablet_size() {
    return __isset_bit_vector.get(__TABLET_SIZE_ISSET_ID);
  }

  public void setTablet_sizeIsSet(boolean value) {
    __isset_bit_vector.set(__TABLET_SIZE_ISSET_ID, value);
  }

  public int getHours_between_doses() {
    return this.hours_between_doses;
  }

  public Prescription setHours_between_doses(int hours_between_doses) {
    this.hours_between_doses = hours_between_doses;
    setHours_between_dosesIsSet(true);
    return this;
  }

  public void unsetHours_between_doses() {
    __isset_bit_vector.clear(__HOURS_BETWEEN_DOSES_ISSET_ID);
  }

  /** Returns true if field hours_between_doses is set (has been assigned a value) and false otherwise */
  public boolean isSetHours_between_doses() {
    return __isset_bit_vector.get(__HOURS_BETWEEN_DOSES_ISSET_ID);
  }

  public void setHours_between_dosesIsSet(boolean value) {
    __isset_bit_vector.set(__HOURS_BETWEEN_DOSES_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((String)value);
      }
      break;

    case PATIENT:
      if (value == null) {
        unsetPatient();
      } else {
        setPatient((Patient)value);
      }
      break;

    case MEDICATION:
      if (value == null) {
        unsetMedication();
      } else {
        setMedication((Medication)value);
      }
      break;

    case TABLETS:
      if (value == null) {
        unsetTablets();
      } else {
        setTablets((Integer)value);
      }
      break;

    case TABLET_SIZE:
      if (value == null) {
        unsetTablet_size();
      } else {
        setTablet_size((Integer)value);
      }
      break;

    case HOURS_BETWEEN_DOSES:
      if (value == null) {
        unsetHours_between_doses();
      } else {
        setHours_between_doses((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case PATIENT:
      return getPatient();

    case MEDICATION:
      return getMedication();

    case TABLETS:
      return Integer.valueOf(getTablets());

    case TABLET_SIZE:
      return Integer.valueOf(getTablet_size());

    case HOURS_BETWEEN_DOSES:
      return Integer.valueOf(getHours_between_doses());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case PATIENT:
      return isSetPatient();
    case MEDICATION:
      return isSetMedication();
    case TABLETS:
      return isSetTablets();
    case TABLET_SIZE:
      return isSetTablet_size();
    case HOURS_BETWEEN_DOSES:
      return isSetHours_between_doses();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Prescription)
      return this.equals((Prescription)that);
    return false;
  }

  public boolean equals(Prescription that) {
    if (that == null)
      return false;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_patient = true && this.isSetPatient();
    boolean that_present_patient = true && that.isSetPatient();
    if (this_present_patient || that_present_patient) {
      if (!(this_present_patient && that_present_patient))
        return false;
      if (!this.patient.equals(that.patient))
        return false;
    }

    boolean this_present_medication = true && this.isSetMedication();
    boolean that_present_medication = true && that.isSetMedication();
    if (this_present_medication || that_present_medication) {
      if (!(this_present_medication && that_present_medication))
        return false;
      if (!this.medication.equals(that.medication))
        return false;
    }

    boolean this_present_tablets = true;
    boolean that_present_tablets = true;
    if (this_present_tablets || that_present_tablets) {
      if (!(this_present_tablets && that_present_tablets))
        return false;
      if (this.tablets != that.tablets)
        return false;
    }

    boolean this_present_tablet_size = true;
    boolean that_present_tablet_size = true;
    if (this_present_tablet_size || that_present_tablet_size) {
      if (!(this_present_tablet_size && that_present_tablet_size))
        return false;
      if (this.tablet_size != that.tablet_size)
        return false;
    }

    boolean this_present_hours_between_doses = true;
    boolean that_present_hours_between_doses = true;
    if (this_present_hours_between_doses || that_present_hours_between_doses) {
      if (!(this_present_hours_between_doses && that_present_hours_between_doses))
        return false;
      if (this.hours_between_doses != that.hours_between_doses)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Prescription other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Prescription typedOther = (Prescription)other;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, typedOther.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPatient()).compareTo(typedOther.isSetPatient());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPatient()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.patient, typedOther.patient);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMedication()).compareTo(typedOther.isSetMedication());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMedication()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.medication, typedOther.medication);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTablets()).compareTo(typedOther.isSetTablets());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTablets()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tablets, typedOther.tablets);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTablet_size()).compareTo(typedOther.isSetTablet_size());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTablet_size()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tablet_size, typedOther.tablet_size);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHours_between_doses()).compareTo(typedOther.isSetHours_between_doses());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHours_between_doses()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hours_between_doses, typedOther.hours_between_doses);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Prescription(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("patient:");
    if (this.patient == null) {
      sb.append("null");
    } else {
      sb.append(this.patient);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("medication:");
    if (this.medication == null) {
      sb.append("null");
    } else {
      sb.append(this.medication);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tablets:");
    sb.append(this.tablets);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tablet_size:");
    sb.append(this.tablet_size);
    first = false;
    if (!first) sb.append(", ");
    sb.append("hours_between_doses:");
    sb.append(this.hours_between_doses);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PrescriptionStandardSchemeFactory implements SchemeFactory {
    public PrescriptionStandardScheme getScheme() {
      return new PrescriptionStandardScheme();
    }
  }

  private static class PrescriptionStandardScheme extends StandardScheme<Prescription> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Prescription struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PATIENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.patient = new Patient();
              struct.patient.read(iprot);
              struct.setPatientIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MEDICATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.medication = new Medication();
              struct.medication.read(iprot);
              struct.setMedicationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TABLETS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tablets = iprot.readI32();
              struct.setTabletsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TABLET_SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tablet_size = iprot.readI32();
              struct.setTablet_sizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // HOURS_BETWEEN_DOSES
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.hours_between_doses = iprot.readI32();
              struct.setHours_between_dosesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Prescription struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.patient != null) {
        oprot.writeFieldBegin(PATIENT_FIELD_DESC);
        struct.patient.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.medication != null) {
        oprot.writeFieldBegin(MEDICATION_FIELD_DESC);
        struct.medication.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TABLETS_FIELD_DESC);
      oprot.writeI32(struct.tablets);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TABLET_SIZE_FIELD_DESC);
      oprot.writeI32(struct.tablet_size);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(HOURS_BETWEEN_DOSES_FIELD_DESC);
      oprot.writeI32(struct.hours_between_doses);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PrescriptionTupleSchemeFactory implements SchemeFactory {
    public PrescriptionTupleScheme getScheme() {
      return new PrescriptionTupleScheme();
    }
  }

  private static class PrescriptionTupleScheme extends TupleScheme<Prescription> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Prescription struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetPatient()) {
        optionals.set(1);
      }
      if (struct.isSetMedication()) {
        optionals.set(2);
      }
      if (struct.isSetTablets()) {
        optionals.set(3);
      }
      if (struct.isSetTablet_size()) {
        optionals.set(4);
      }
      if (struct.isSetHours_between_doses()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetId()) {
        oprot.writeString(struct.id);
      }
      if (struct.isSetPatient()) {
        struct.patient.write(oprot);
      }
      if (struct.isSetMedication()) {
        struct.medication.write(oprot);
      }
      if (struct.isSetTablets()) {
        oprot.writeI32(struct.tablets);
      }
      if (struct.isSetTablet_size()) {
        oprot.writeI32(struct.tablet_size);
      }
      if (struct.isSetHours_between_doses()) {
        oprot.writeI32(struct.hours_between_doses);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Prescription struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.id = iprot.readString();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.patient = new Patient();
        struct.patient.read(iprot);
        struct.setPatientIsSet(true);
      }
      if (incoming.get(2)) {
        struct.medication = new Medication();
        struct.medication.read(iprot);
        struct.setMedicationIsSet(true);
      }
      if (incoming.get(3)) {
        struct.tablets = iprot.readI32();
        struct.setTabletsIsSet(true);
      }
      if (incoming.get(4)) {
        struct.tablet_size = iprot.readI32();
        struct.setTablet_sizeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.hours_between_doses = iprot.readI32();
        struct.setHours_between_dosesIsSet(true);
      }
    }
  }

}

